### ISSUE TITLE
Question about missing Pins on UM-FT2232

### ISSUE THREAD

**Issue by explit28** [mariusgreuel/um-ft2232h#1]
Hello @mariusgreuel 

Maybe you can help me. I use the UM-FT2232 Module instead the original FT2232 Mini Module.
I need to connect this Pins, which are missing on your pinout (which is great help by the way, cool that you created it)

V3V3 to VIO strap
VBUS to VCC strap
V3V3 to VIO strap (2)

#https://github.com/yeokm1/graphics-gremlin-hdmi/issues/4

**Comment by tswaehn** [comment]
@explit7 actually for me is not clear, what the question is about. the FT2232 requires to set correct voltages to VIO and VCC. which on this board is 3.3V.

maybe I am misunderstanding your request.

**Comment by explit28** [comment]
> @explit7 actually for me is not clear, what the question is about. the FT2232 requires to set correct voltages to VIO and VCC. which on this board is 3.3V.
> 
> maybe I am misunderstanding your request.

My question is about the difference between the original FTDI FT2232 Mini Module and ELV UM-FT2232.
The Chip is the same, but the Pinout is different. The original FTDI FT2232 Mini Module has more Pins.
![Screenshot 2024-06-17 at 01-17-53 Flashing bitstream · yeokm1_graphics-gremlin-hdmi Wiki](https://github.com/mariusgreuel/um-ft2232h/assets/11852348/3235e2b3-b684-4e91-9361-04fdc0e02f32)

While i know where to connect 

CN2 pin 14 	SPI cable pin 1 	CS
CN2 pin 16 	SPI cable pin 2 	CDONE
CN2 pin 7 	SPI cable pin 3 	SCK (serial clock)
CN2 pin 15 	SPI cable pin 4 	CRESET
CN2 pin 9 	SPI cable pin 5 	CIPO (controller in, peripheral out)
CN2 pin 2 	SPI cable pin 6 	GND
CN2 pin 10 	SPI cable pin 7 	COPI (controller out, peripheral in)

I have no idea, which pins i need to use, when i want to use this Pins:

CN2 pin 1 	CN2 pin 11 	V3V3 to VIO strap
CN3 pin 1 	CN3 pin 3 	VBUS to VCC strap
CN2 pin 3 	CN3 pin 12 	V3V3 to VIO strap (2)

Maybe they are just missing on UM-FT2232. Flashing works, but i am afraid, that i can give more current to the SPI flash, than it can manage....

**Comment by tswaehn** [comment]
please compare: this is the board of this repo:

> Here is the pinout of the FTDI FT2232H module [UM-FT2232H](https://de.elv.com/elv-highspeed-mini-usb-modul-um-ft2232h-komplettbausatz-099347) distributed by [ELV Germany](https://de.elv.com/):

![image](https://github.com/mariusgreuel/um-ft2232h/assets/891378/1d64e75a-17ce-4874-9ffb-b51567c0f287)

@explit7 to answer your question, you may need to provide schematics for your proposed board

**Comment by explit28** [comment]
Hello @tswaehn - Yes i have the same board.

As i previously mentioned, this Pins are missing on UM-FT2232H
V3V3
VBUS

Flashing seems to working stable, so i think we can close the issue..
